package com.extrawest.ocpi.model.security;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Set;

import static com.extrawest.ocpi.model.security.Permission.*;

@AllArgsConstructor
@Getter
public enum Role {
    CPO(Set.of(CDRS_SENDER,
            CHARGING_PROFILES_RECEIVER,
            COMMANDS_RECEIVER,
            CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_RECEIVER,
            LOCATIONS_SENDER,
            SESSIONS_SENDER,
            TARIFFS_SENDER,
            TOKENS_RECEIVER,
            VERSIONS_SENDER, VERSIONS_RECEIVER)),

    EMSP(Set.of(CDRS_RECEIVER,
            COMMANDS_SENDER,
            CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_RECEIVER,
            LOCATIONS_RECEIVER,
            SESSIONS_RECEIVER,
            TARIFFS_RECEIVER,
            TOKENS_SENDER,
            VERSIONS_SENDER, VERSIONS_RECEIVER)),

    HUB(Set.of(CDRS_RECEIVER, CDRS_SENDER,
            CHARGING_PROFILES_RECEIVER, CHARGING_PROFILES_SENDER,
            COMMANDS_RECEIVER, COMMANDS_SENDER,
            CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_SENDER,
            LOCATIONS_RECEIVER, LOCATIONS_SENDER,
            SESSIONS_RECEIVER, SESSIONS_SENDER,
            TARIFFS_RECEIVER, TARIFFS_SENDER,
            TOKENS_SENDER, TOKENS_RECEIVER,
            VERSIONS_SENDER, VERSIONS_RECEIVER)),

    NSP(Set.of(CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_RECEIVER,
            LOCATIONS_RECEIVER,
            TARIFFS_RECEIVER,
            VERSIONS_SENDER, VERSIONS_RECEIVER)),

    NAP(Set.of(CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_RECEIVER,
            LOCATIONS_RECEIVER, LOCATIONS_SENDER,
            TARIFFS_RECEIVER, TARIFFS_SENDER,
            VERSIONS_SENDER, VERSIONS_RECEIVER)),

    SCSP(Set.of(CHARGING_PROFILES_SENDER,
            CREDENTIALS_SENDER, CREDENTIALS_RECEIVER,
            HUB_CLIENT_INFO_RECEIVER,
            SESSIONS_RECEIVER,
            VERSIONS_SENDER, VERSIONS_RECEIVER));

    private final Set<Permission> permissions;

}