name: Create a GitHub Release with release details specified

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false